word_list = [
    "GOKU", "NARUTO", "LUFFY", "SAITAMA", "DEKU", "ITACHI", 
    "EREN", "LEVI", "TANJIRO", "NEZUKO", "BULMA", "SAKURA", 
    "ZORO", "SANJI", "GOHAN", "KAKASHI", "ROHAN", "GON", 
    "KILLUA", "HINATA", "SUPERMAN", "BATMAN", "THOR", 
    "WONDERWOMAN", "SPIDERMAN", "IRONMAN", "HERCULES", 
    "ZEUS", "POSEIDON", "DRAGON", "UNICORN", "PHOENIX",
    "PYTHON", "JUPYTER", "CODE", "PROGRAM", "COMPUTER",
    "SCIENCE", "PYRAMID", "OCEAN", "MOUNTAIN", "RIVER",
    "FOREST", "DESERT", "CITY", "VILLAGE", "COUNTRY",
    "FRIENDSHIP", "HAPPINESS", "EXCITEMENT", "ADVENTURE",
    "KNOWLEDGE", "LEARNING", "HUMOR", "CREATIVITY", "MAID",       "PROVIDE", "USEFUL", "WHISPER", "SPOOKY", "BLADE",            "COMMON", "PAT", "EMPTY", "COWS", "STROKE", "BOIL",           "SUDDEN", "REQUEST", "SNAKES", "DEMON", "SNOW", "LIVE",       "PANCAKE", "CHEAP", "LWED", "LOCK", "PASS"
]